### ISSUE TITLE
outdated brapi-resources.xml/json

### ISSUE THREAD

**Issue by martinbaste** [plantbreeding/API#110]
I've tested the resources available in the current version of brapi-resources and found some that are not available at the time of this writing (James Hutton Institute, BMS, Cassava-test needs auth, etc). What should we do with them?

I can submit a PR removing those that are not working anymore. I also know some other resources, but I am not affiliated with them so I don't know if they want to appear here.

**Comment by imilne** [comment]
The Hutton one just needs updated. We'll get on it...

**Comment by BrapiCoordinatorSelby** [comment]
Closing this issue. Not a problem with the spec.

I believe BRAVA has created a good solution to this problem. Before now there was no incentive for groups to keep there implementations updated because the information was not being used anywhere except as developer reference documentation. Now there is an incentive to keep your implementation info updated so you can pass the automated BRAVA test suite. 

That said, it is on my TODO list to make existing public BrAPI resources known and available to a wider audience. So I'll be looking to make the update process easier, and the list more publicly visible.
