### ISSUE TITLE
'/brapi/v1/attributes/categories/' Page parameter documentation goes against standard

### ISSUE THREAD

**Issue by BrapiCoordinatorSelby** [plantbreeding/API#121]
The page parameter explicitly calls out that "The first page is 1, not 0"
The rest of the BrAPI spec has 0 indexed pagination. Does this one need to be different?

Contributors @naymesh @lukasmueller @martinbaste 

[/brapi/v1/attributes/categories/](https://github.com/plantbreeding/API/blob/master/Specification/GermplasmAttributes/ListAttributeCategories.md)

**Comment by barrow-wight** [comment]
"Exceptions" are very irritating to a consumer (coder) attempting to use an API. Consistency across calls is much better and leads to fewer "bugs".

**Comment by mverouden** [comment]
I agree with @barrow-wight, that the BrAPI specifications should be consistent. Currently I am adapting the BrAPI r package to work with IBP Breeding Management System and came across inconsistencies in their implementation with respect to paginatio (they used a 1 base page indexing instead of 0 as specified). Trying to adapt to all sorts of special cases is not desirable when developing software.
