### ISSUE TITLE
Observation Unit fields 'X' and 'Y' are not clearly defined

### ISSUE THREAD

**Issue by BrapiCoordinatorSelby** [plantbreeding/API#142]
The fields called 'X' and 'Y' are not clearly defined. I assume they refer to the row and column coordinates of a particular Observation Unit. 
If this assumption is correct, I propose changing the names to 'rowNumber' and 'columnNumber'.

**Comment by nahuel-soldevilla** [comment]
I think if we compare the Cartesian coordinates to a table, it makes more sense for X to be a column

**Comment by cpommier** [comment]
It depends if the type of the coordinate system are row and column.
It can be row and stock for instance.
The idea is to have those to generic X and Y and to give them a label in XName and Yname.

Cyril






____________________________________________________

Cyril Pommier
*New Email* cyril.pommier@inra.fr<mailto:cyril.pommier@inra.fr>
URGI<https://urgi.versailles.inra.fr>     Information System and Data integration deputy leader
               Phenotype thematic leader
ORCID: orcid.org/0000-0002-9040-8733<http://orcid.org/0000-0002-9040-8733>
Tel. : +33 1 (0)1 30 83 38 36
Mobile : +33 1 (0)6 64 30 81 85
___________________________________________________



Le 1 déc. 2017 à 21:18, Nahuel Soldevilla <notifications@github.com<mailto:notifications@github.com>> a écrit :


I think if we compare the Cartesian coordinates to a table, it makes more sense for X to be a column

**Comment by nickmorales** [comment]
we had interpreted X and Y to mean column number and row number. for our system, row number and column number only mean the physical position of the plot in the field, if a grid is overlaid on the field.

**Comment by cpommier** [comment]
X and Y, in our system, can refer to many observation unit localization system.
- In a field, it can be row and column number, plus optionally  distance in meters from the origin. In this case it is X m and Ym in our system.
- For grape, it can be row and rootstock number (close to the notion of individual below). In other word its the corrdinate of a single individual in row/individual position system.
- For fruit Trees it can be row and column, or indivuidual number.
- In field or perenial plants (forest) it can be lattitude and longitude (GPS) of a given individual or microplot.

**Comment by BrapiCoordinatorSelby** [comment]
can it be something like `positionCoordinateX` and `positionCoordinateY`? Plus a `positionCoordinateType` which can better define the scope and units of the values given?

So we basically still have free form X and Y but clients will know how to display them properly, and data from 2 systems won't be mixed arbitrarily. And I wont get confused while reading the spec about if X and Y refer to coordinates, dimensions, chromosomes, or letters of the alphabet lol.

**Comment by nickmorales** [comment]
We could potentially give GPS coordinates for plots as well but the api
would need to clearly define what format to use. The api should of course
be a common and consistent language, so defining exactly what x and y is is
important.

On Dec 6, 2017 11:44 PM, "Peter Selby" <notifications@github.com> wrote:

can it be something like positionCoordinateX and positionCoordinateY? Plus
a positionCoordinateType which can better define the scope and units of the
values given?

So we basically still have free form X and Y but clients will know how to
display them properly, and data from 2 systems won't be mixed arbitrarily.
And I wont get confused while reading the spec about if X and Y refer to
coordinates, dimensions, chromosomes, or letters of the alphabet lol.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/plantbreeding/API/issues/142#issuecomment-349799915>,
or mute the thread

**Comment by BrapiCoordinatorSelby** [comment]
I added these options for coordinate types/units. I think this covers all the options we discussed here, If there are any more that need to be added, please open a new issue. 

          LONGITUDE - ISO 6709 standard, WGS84 geodetic datum. See "Location Coordinate Encoding" for details
          LATITUDE - ISO 6709 standard, WGS84 geodetic datum. See "Location Coordinate Encoding" for details
          PLANTED_ROW - The physical planted row number 
          PLANTED_INDIVIDUAl - The physical counted number, could be independant or within a planted row
          GRID_ROW - The row index number of a square grid overlay
          GRID_COL - The column index number of a square grid overlay
          MEASURED_ROW - The distance in meters from a defined 0th row
          MEASURED_COL - The distance in meters from a defined 0th column
