### ISSUE TITLE
For consistency, should /locations be /locations-search and others?

### ISSUE THREAD

**Issue by martinbaste** [plantbreeding/API#168]
Following #29 
/locations could be /locations-search. /trials also could be /trials-search (as we have /studies-search)
Maybe /maps too (it accepts parameters)?

Don't count this as a vote in favor, I'm not sure I like -search nomenclature anyway, just wondering what people think about this.

**Comment by BrapiCoordinatorSelby** [comment]
The ideal purest RESTful way would look something like this:

* GET /studies 
    * return all studies 
* GET /studies?queryParam=something 
    * return filtered list of studies 
* GET /studies/{studydbid} 
    * return 1 specific study determined by primary key
* POST /studies-search {complex search object} 
    * returns ID for the new complex search object (search happens asynchronously)
* GET /studies-search/ID 
    * returns the search results of the complex query as a list of studies

However, I'm hesitant to enforce this type of searching scheme because it would require some significant effort for anyone who has already implemented a set of search calls.

Coming back to your original question, /locations /trials and /maps are actually better from a purest RESTful perspective because they correctly implement 1, 2, and 3 from above. So this becomes a debate between if we change these 3 calls to match the other calls in BrAPI, or do we change the other calls to become more RESTful? There are valid arguments on each side...

**Comment by c5sire** [comment]
Good topic for discussion. My inclination is in favor of becoming as RESTful as possible as Peter describes. One more argument in favor is that it makes it easier for any new comer to learn and for everyone easier to remember if it is just standard practice.

**Comment by cpommier** [comment]
it could be for a version 1.3, but it is a breaking change so it might be better as a version 2 no ? On the other hand, the impact is probably not very strong.

**Comment by guignonv** [comment]
I would support it if it was in v1.3.
+1

**Comment by BrapiCoordinatorSelby** [comment]
tentatively adding to v1.3 project list

I'd like feedback from a larger group about this. The biggest implementation change here is the need to store search results from POST search calls. This also means a proper authentication scheme must be implemented to make these POST search calls because you have database manipulation. And, this changes the POST search calls from a synchronous call to an asynchronous call, which is not easily backwards compatible. 

Few people off the top of my head, representing a wider range of active BrAPI implementations:
@lukasmueller @jeback1 @nickmorales @philipglaser @nikkicarumba @ClayBirkett @imilne @nahuel-soldevilla 
If you think of anyone else who should weigh in on this, call them out!
