### ISSUE TITLE
gemplasmDbId with "/" does not work : DOI and PUI as DbId

### ISSUE THREAD

**Issue by cpommier** [plantbreeding/API#186]

**Comment by gcornut** [comment]
Discussion started on https://github.com/plantbreeding/API/issues/85

**Comment by BrapiCoordinatorSelby** [comment]
If I remember correctly, this issue was opened so we could document this special case for others who might run into the same problem. I have added it to the [BrAPI Wiki](https://wiki.brapi.org/index.php/Best_Practices#DbIds_and_Names) under "Best Practices" so I will close the issue now.

For anyone who has found themselves reading this issue, here are my thoughts on this particular problem:

the BrAPI germplasm object has an explicit field `germplasmPUI`, and both germplasm-search calls (GET and POST) have a search parameter for `germplasmPUI`. Use this field for communicating the DOI url and use a different primary key for your DbId. If an integer or UUID key is not available, maybe consider storing the hashed form of the DOI in the database. It could be used as the DbId, and used as a double check of the accuracy of the PUI in some cases. 
This seems like the easier solution than encoding the URL, but as long as the DbId is a valid string and a unique identifier in your system, BrAPI doesn't care how you do it.
