### ISSUE TITLE
Partially implemented calls

### ISSUE THREAD

**Issue by GuilhemSempere** [plantbreeding/API#199]
In some cases a given server implementation may be unable to fully implement certain calls. For example /markers-search supports a matchMethod parameter thay takes values such as exact, case_insensitive or wildcard. Depending on the back-end structure it may be impossible to search using wildcard. How do we deal with that?

Also, just writing this, I'm realizing that case_insensitive could actually be combined with exact or wildcard, all depends on everyone's interpretation. Don't want to push for any behaviour, just pointing out it's sort of ambiguous.

**Comment by guignonv** [comment]
After our last meeting, I noted some people were using the "matchMethod" parameter but I realized I dropped it a time ago (I though it was removed from the specs). And when we had the discussion about advanced searches, we marked which fields would require such kind of match. So I had a look into the documentation today and didn't find the place where the use of the "matchMethod" parameter is described except for the marker-search call where it says:

> matchMethod (optional, string, wildcard) ... Possible values are 'case_insensitive', 'exact' (case sensitive), 'wildcard' (which is case insensitive). Wildcard uses both '*' and '%' for any number of characters and '?' for one character matching. Default is exact.

It used to be in the gremplasm-search or germplasm details calls but it is not anymore.
So I think either we actually did remove that parameter a long time ago and it still appears on some places but should not... or we are missing a detailed documentation about it, just like Guilhem is mentioning.

Many questions about this: would it be required? Used or required by which calls? ...on which fields? Does it make sense to implement it on some fields and not some others? Could we combine wildcard and case-sensitive/insensitive? What are the special characters? How to escape them? (and I also remember some parts of old discussions about also including a "fuzzy" type search, "begin_with" and "end_with" were removed because "wildcard" would do the same, how many wildcard would be supported in a user query, would we have a joker character,...).

**Comment by BrapiCoordinatorSelby** [comment]
to answer @GuilhemSempere 's original issue:
This question has come up in other places about not being able to handle certain input parameters. I recommend accepting the parameter as a valid input, and then ignoring it when performing any logic or database query.  
Also, as BrAPI gets bigger and more complex, I've been recommending that anyone who is building a server side implementation should make their own documentation page. This allows you to document any minor differences between the official BrAPI spec and your implementation, and it allows you to document any additional services you might have available which are not part of BrAPI.
