### ISSUE TITLE
phenotype-search/csv and phenotype-search/tsv do not use "datafiles" key

### ISSUE THREAD

**Issue by nickmorales** [plantbreeding/API#249]
i thought that the datafiles key in metadata was to be used when a file is requested from brapi?

so the response of /phenotype-search/csv would be something like:
{"metadata":{"datafiles":["https://myserver.com/static/documents/myfile.csv"],"status":[],"pagination":{"totalPages":0,"pageSize":10,"totalCount":0,"currentPage":0}},"result":{}}

its not too clear to me, but i think that was the motivation for having the datafiles key in metadata, so that potentially any call could request format=csv or format=tsv or format=json as a parameter. maybe things have evolved since then though.

similarly it seems to be the motivation for the datatypes key in the calls call, so that people are aware which formats are valid

**Comment by BrapiCoordinatorSelby** [comment]
It was my understanding that "datafiles" was intended to be used for supplementary data such as images or reference documentation. 
I feel the content of the response should contain whatever primary data you requested. If you request that primary data in CSV format, then the response body should contain CSV data. 

Regarding the "datatypes" key in calls call, I'd like to move toward a model more like phenotypes-search where each return format is designated by a separate call. This means the "datatypes" key will become unnecessary, or at least can become a single string instead of an array.

**Comment by BrapiCoordinatorSelby** [comment]
These calls have been deprecated in v1.3 in favor of a `/search/observationtable` where this issue has been addressed

You should use the `Accept` header on the request to specify the format (MIME type) of the results. In the response, the `Content-Type` header should match the requested format (MIME type).
Examples:
"Accept": "application/json" will return a JSON object with a 2 dimensional array of data
"Accept": "text/csv" will return the data in a CSV format (not JSON)
