### ISSUE TITLE
Get Observations for a Study "uploadedBy" source?

### ISSUE THREAD

**Issue by theProgrammerJack** [plantbreeding/API#282]
The response object for the `GET /brapi/v1/studies/{studyDbId}/observations` call contains a field `"uploadedBy": "dbUserId"` in every observation object, however there appears to be no place to specify this when creating an observation with the corresponding `PUT` call. Where does the value of `uploadedBy` come from?

**Comment by BrapiCoordinatorSelby** [comment]
BrAPI V2.0
this issue is resolved.
`collector` and `uploadedBy` are standardized across GET and POST calls

BrAPI V1.3
Yes `collector` and `operator` were meant to correspond with each other. 
The original intention with `uploadedBy` is that since every request should be tied to a user account with an authorization token, then the server should be responsible for working that field out. Now, in V2, the server has the option of taking the value as given, or tying to the correct user account ID.
