### ISSUE TITLE
Observation Variables scale.class vs scale.datatype

### ISSUE THREAD

**Issue by theProgrammerJack** [plantbreeding/API#283]
On Apiary, the "Observation variable data response" chart lists `scale.class` as the class of the scale, listing a limited set of options for it's value. None of the calls that return observation variables seem to have this property, however, instead having a `scale.datatype` property that is not listed in the chart. Is one of these properties listed incorrectly, or if not, which one really defines the type of data that should be collected for a variable?

**Comment by BrapiCoordinatorSelby** [comment]
fixed in V1.3
Apiary and SwaggerHub are now aligned, `scale.datatype` is the correct property to use, with an enumerated set of accepted values taken from the Crop Ontology:
 <p>"Code" -  This scale class is exceptionally used to express complex traits. Code is a nominal scale that combines the expressions of the different traits composing the complex trait. For exemple a severity trait might be expressed by a 2 digit and 2 character code. The first 2 digits are the percentage of the plant covered by a fungus and the 2 characters refer to the delay in development, e.g. "75VD" means "75%" of the plant is infected and the plant is very delayed.</p>
        <p>"Date" - The date class is for events expressed in a time format, e.g. yyyymmddThh:mm:ssZ or dd/mm/yy</p>
        <p>"Duration" - The Duration class is for time elapsed between two events expressed in a time format, e.g. days, hours, months</p>
        <p>"Nominal" - Categorical scale that can take one of a limited and fixed number of categories. There is no intrinsic ordering to the categories</p>
        <p>"Numerical" - Numerical scales express the trait with real numbers. The numerical scale defines the unit e.g. centimeter, ton per hectar, branches</p>
        <p>"Ordinal" - Ordinal scales are scales composed of ordered categories</p>
        <p>"Text" - A free text is used to express the trait.</p>
