### ISSUE TITLE
Need xref and additionalinfo fields in germplasm model / object

### ISSUE THREAD

**Issue by dlebauer** [plantbreeding/API#292]
I'd like to 

1. add references to the same germplasm in multiple databases using xref
2. add latitude and longitude for accession source using additionalinfo or specific latitude/longitude fields

**Comment by BrapiCoordinatorSelby** [comment]
BrAPI V2.0
`additionalInfo` field was added AND `germplasmOrigin` field has coordinate information. 
I added `xref` to germplasm, but @cpommier is correct, there needs to be more thought and standardization of `xref` usage throughout BrAPI. Closing this issue because its requirements were met, but expect possible future changes to `xref`
