### ISSUE TITLE
Backward compatibillity between minor versions

### ISSUE THREAD

**Issue by gcornut** [plantbreeding/API#349]
First I'd like to say the work done on the latest minor versions of the BrAPI is great. It's nice to see all the clean up and simplification made to the API ! :+1: 

However, as I'm working on server and client implementations of the BrAPI I was wondering what policy was employed when designing new minor version concerning the backward compatibility with v1.

It seem that deletions are not permitted in minor version and are just replaced by deprecations to make sure v1 client can still query v1.x endpoints which is nice.

But I've seen some backward compatibility breaks like the format of the `seasons`  field in study which switch from an array of string to an array of object (in the `/brapi/v1/studies` but not in the `/brapi/v1/studies/{studyDbId}` call). I don't question the value of such a modification but it implies a different processing of the field in v1 vs v1.3.

Does this mean BrAPI client should expect additions and possibly modifications (of calls, fields, parameters, etc.) but no deletions in new minor versions of BrAPI?

**Comment by BrapiCoordinatorSelby** [comment]
Thanks @gcornut! We certainly have come a long way!

The policy is to maintain backward compatibility between all minors within a major version, just as you have described. This is possible and trivial in most cases, however, field types are one of the places which make things difficult. To answer your question, yes a BrAPI client should expect additions, but no deletions.

In some cases (particularly V1.0 and V1.1), some fields were not defined properly with a type, or they were defined with multiple conflicting types in different parts of the documentation. Now that we have formally moved to the OpenAPI 3 documentation standard where typing is strictly enforced, I hope these sorts of issues will go away for future enhancements.
In some cases, like the one you describe concerning `seasons`, it is simply a mistake (or intentional decision) on my part. During PAG one of the things the community discussed was having some kind of alpha/beta versioning with a review process. This should help counteract my human nature to make mistakes. This past year has been very focused on paying technical debt, cleaning, and standardizing. Moving forward, things will shift to focus on stability and enhancing functionality.

In the short term, my recommendation would be to create some documentation which represents the reality of the implementations you are building. This gives you a place to document any differences between your implementation and the official spec. For example, this allows you to make your own decisions around these backward compatibility issues and document exactly what field types your server will return.
