### ISSUE TITLE
Germplasm call Repeated properties  -> properties species and germplasmSpecies & genus and germplasmGenus

### ISSUE THREAD

**Issue by netbofia** [plantbreeding/API#351]
I've marked the properties in question in result.data array, that  look like they are the same.
Why is there germplasmGenus and genus in which use case would they be different?
The same question for germplasmSpecies and species

```
    "result": {
        "data": [
            {
                "accessionNumber": "A000003",
                "acquisitionDate": "2001-01-01",
                "biologicalStatusOfAccessionCode": 500,
                "breedingMethodDbId": "bm1",
                "commonCropName": "G000003",
                "countryOfOriginCode": "COUNTRY1",
                "defaultDisplayName": "G000003",
                "documentationURL": "https://brapi.org",
                "donors": [],
                "genus": "Fructus",                   //!!!!!!!!!!!!!!!!****!!!!!!!!!!
                "germplasmDbId": "3",
                "germplasmGenus": "Fructus",  //!!!!!!!!!!!!!!!!****!!!!!!!!!!
                "germplasmName": "Name003",
                "germplasmPUI": "http://pui.per/accession/A000003",
                "germplasmSpecies": "novus",  //!!!!!!!!!!!!!!!!****!!!!!!!!!!   
                "instituteCode": "PER001",
                "instituteName": "INST1",
                "pedigree": "A000001/A000002",
                "seedSource": "A000001/A000002",
                "species": "novus",                   //!!!!!!!!!!!!!!!!****!!!!!!!!!!
                "speciesAuthority": "L",
                "subtaxa": "subtaxa",
                "subtaxaAuthority": "N",
                "synonyms": [
                    "variety 1"
                ],
```

**Comment by netbofia** [comment]
Just saw in the schema that genus and species are deprecated on v1.3. 
Suggestion remove them from example in branch v1.3

**Comment by BrapiCoordinatorSelby** [comment]
I removed the deprecated keys from the example response to make the documentation clearer in V1.3.
This change will only be reflected in GitHub and not Swagger or Apiary because 1.3 has been "published" and can not be edited. I can delete the published version and republish a fix if necessary, but I don't feel this issue is critical enough to break that code freeze. 

In V2.0, I have attempted to design things in such a way so the example value and current schema are always in sync, which will hopefully reduce these sorts of discrepancies in the future.
