### ISSUE TITLE
Add Lot notion to Germplasm

### ISSUE THREAD

**Issue by cpommier** [plantbreeding/API#365]
According to https://en.wikipedia.org/wiki/Germplasm a germplasm is a living thing. Therefore, we need a notion of lot : 
- Variety : golden
- Accession : golden_inra (no physical existence)
- lot : bag of seeds, a single tree (ie clone)

This notion of lot is currently present in observation unit xref. It would make sense to have a lotDbId in germplasm.
NB: variety1--*Accession1--*lot
Therefore with the proposed approach, we could have multiple germplasm with the same accessionNumber and different germplasmDbId.

**Comment by cpommier** [comment]
Note that the answer to that point might be that in brapi, germplasm are in fact accession and therefore we could rename germplasm to accession

**Comment by PapoutsoglouE** [comment]
We have a use case that could also benefit from such additional specifications about the germplasm.  
In specific, we have potato experiments where it is important to track the products of specific crosses (even between the same parents) across different studies, and we do this in our database with a genotype ID field.

**Comment by dovivi** [comment]
Related to #266 ?

**Comment by cpommier** [comment]
Yes that's related, be here the question is more: "is germplasm an accession or a seedlot"
Semantically, germplasm = seedlot. In the current implementation, the brapi.germplasm is an accession.

**Comment by nickmorales** [comment]
in our database we have distinct concepts for these things:

accession: maps directly to germplasm in BrAPI. it is abstract in the sense it has no physical inventory or location. it has a pedigree and is associated to parents. it can be associated to plots/plants/etc in the field trial.

seedlot: has a seed count/weight in grams, has a storage location. is linked directly to an accession or cross, indicating the "contents" of the seedlot. it can be associated to plots/plants/etc in field trials where seed from the seedlot was planted. seedlots can be transacted between seedlots (e.g. i moved seed from a seedlot at IITA to a seedlot at Cornell), into plots (e.g. i planted seed from a seedlot into a plot), etc.

cross: a specific crossing event between germplasm. is linked to accessions that were crossed together. progeny accessions can be produced from a cross (builds pedigree also). seedlots can have contents from a cross. cross can have properties linked to it like number of flowers, pollination date, flower date, etc.

**Comment by guignonv** [comment]
I would join @nickmorales point of view: accessions are abstract, not physical. "Germplasm" represents the pool of accessions.

Physical instances are for me "samples", which can be either a seed, a seedlot, a leaf, a full plant.
In my vision of things, from a computer science perspective, "germplasm" is a kind of "namespace" where you have "accessions" which are "class" and each physical individual or part of it are "class instances".

These notions are often discussed and usually, people have different (strong) point of view on those. So I doubt we could agree on something here. :-S But IMHO, I think lotDbId should be added to samples rather than germplasm. "accessionNumber" should be "unique"* for germplasm call (*:unique for a given collection).

**Comment by cpommier** [comment]
Creating a new, less philosophical, issue
