### ISSUE TITLE
Handle URI/PUI in DbIds, aka URL friendly entityDbId

### ISSUE THREAD

**Issue by cpommier** [plantbreeding/API#369]
# Use case
several entities (study, germplasm, observationVariable, observationUnit) can be referred both by PUI (URI, DOI) and DbId. An emerging practice is to put the PUI in the DbId field
```json
"studyDbId":"http://phenome-fppn.fr/maugio/2015/"
```
But this generate a lot of troubles if we want to get study details as the web server will not know to handle slashes:
```
/brapi/v1/studies/http://phenome-fppn.fr/maugio/2015/
```
slashs URL encoding doesn't really solve the problem has tomcat will block it anyway. Double url encoding works but is not robust and the client must be aware of that implementation detail

# Considered solution
During BrAPI hackathon @WUR, the following solutions have been proposed:
## Promote URL friendly entityDbId
all studyDbId, germplasmDbId must be URL safe, without slashes or non ASCII characters. 
A safe fall back can be UUID or base64 encoding.

## Add PUI/@id to all entity with DbId
```
entity{
entityDbId
entityPUI or @id
}
```

## Get entity details by PUI
Add to the existing entity calls:
`/brapi/v1/studies/{studyDbId}`
Additional calls:

`/brapi/v1/studies/?studyPUI={studyPUI}`
or
`/brapi/v1/studies/?id={@id}`

**Comment by dauglyon** [comment]
I'm skeptical of using `@id` for this purpose as we move toward JSON-LD. I have two worries. One, that using it in such a way makes referencing one brapi entity from another more complicated (the url to access the node is not the same to identify it). Two, I worry about  misinterpretation of this field as simply "the url that this entity's further info is located at" (like #187) rather than as an "immutable node identifier". This is important because the same JSON-LD entity (representing the same thing), "shouldn't" be returned with a different `@id`.

[Importantly, `@id` only "may" resolve to a representation of the node it identifies, but "should" identify the node](https://www.w3.org/TR/2014/REC-json-ld-20140116/#node-identifiers) while [`url` is defined in less certain terms about such matters.](https://schema.org/url) ("may" is weaker than "should" for w3 standards)

 Perhaps it would be better to strictly define the `@id` field as a brapi call, which also enables more explicit linking between BrAPI calls, and use [`url`](https://schema.org/url) for the usecase above.

**Comment by buymel** [comment]
Hi,
We (INRA-URGI/GnpIS) are concerned by this url handling case in endpoint implementation with PHIS team. We propose to test the solution of adding new call **/brapi/v1/studies/?studyPUI={studyPUI}**. plus a studyPUI field in the study response. If another approach is chosen for future version, let us know so we can adapt our client and servers.

**Comment by BrapiCoordinatorSelby** [comment]
@buymel Yup I talked to @cpommier at the last hackathon and I think that is the best approach right now. I haven't gotten to it yet, but that will be the expected behavior in BrAPI V2.0
