### ISSUE TITLE
Pagination: Page number needs to be string and it might need "nextPage" field.

### ISSUE THREAD

**Issue by vg249** [plantbreeding/API#372]
Current standard assumes that the page number is a Integer which starts at 1 and increase until last page. Please feel free to correct me if i am wrong. But, there could be a use case where Page is identified by an Index and Server may need to send nextPage index in currentPage. In that case, a pageNumber being a String and nextPage field would help.

**Comment by BrapiCoordinatorSelby** [comment]
This issue was discussed by the BrAPI Review Board and a formal consensus was reached.
BrAPI paging will continue to be a zero based index number. Any kind of "nextPage" logic will need to be handled as a custom modification by the server implementation. The primary reason for this decision was to maintain the simplicity and flexibility of the BrAPI standard. It is recognized that there are some use cases where this type of paging could become a performance problem, but a vast majority of use cases will work as expected. 

The 'currentPage' field will remain an integer in V2.0.
