### ISSUE TITLE
pluralize germplasm search request field GermplasmGenus to GermplasmGenera

### ISSUE THREAD

**Issue by bellerbrock** [plantbreeding/API#388]
Describes a " List of Genus names to identify germplasm". Plural Genera would fit better!

Related to #176

**Comment by BrapiCoordinatorSelby** [comment]
You are technically correct ... however I don't like this change because it makes things unnecessarily more confusing. I did a quick, informal poll around the office here and no one immediately knew what I meant by "germplasm genera". Also, #176 is about having consistency between the Germplasm Object and the Germplasm Search Request Object. "Genera" is technically the plural form, but this makes it less clear that "Genera" is linked to "Genus" in the Germplasm Object. 

I am rejecting this change. If anyone feels strongly that this change needs to occur, please reach out to me.
