### ISSUE TITLE
Change occurrences of searchResultsDbId to searchResultDbId

### ISSUE THREAD

**Issue by nahuel-soldevilla** [plantbreeding/API#394]
In `Specification/Components/Responses/successfulSearchResponse.yaml` it's 
`searchResultDbId` (which I think is correct, and brapijs is expecting this string) but in other files (params and url strings) we have searchResult**s**DbId.
Also in `brapi-v2-dev` branch.

@BrapiCoordinatorSelby Should we normalize it to the former? Let me know if I can help with a PR _(I should change only the *.yaml files, right? the README's are generated)_

cc @MFlores2021

**Comment by BrapiCoordinatorSelby** [comment]
Good catch @nahuel-soldevilla 
I think the plural `searchResultsDbId` sounds more natural in English, so I will standardize to that. 
The only place this really matters is in `successfulSearchResponse.yaml` because this is the only time the keyword will be present in the JSON. All other occurrences throughout the documentation are used as URL path parameters. These are placeholders and in practice they should be replaced by the actual value of the DbId. (ex `/search/germplasm/{searchResultsDbId}` should become `/search/germplasm/551ae08c`) But you are correct, the documentation should have everything standardized to avoid confusion.


> I should change only the *.yaml files, right? the README's are generated

Yes this is correct. PR's are always appreciated!
