### ISSUE TITLE
Having only the MCPD code is not very user friendly. 

### ISSUE THREAD

**Issue by cpommier** [plantbreeding/API#402]
https://github.com/plantbreeding/API/blob/eae9433880153c7d0f87509126a9fd72800b9bec/Specification/BrAPI-Germplasm/Germplasm/Schemas/GermplasmNewRequest.yaml#L53
In the line above, we have only the MCPD code (ie the 100 of "100) Wild") which is near impossible to use for users. Should we have rather the code + name or rather stick to the code only? In the latter case, it might be interesting to include in the spec a json object containing all the mappings for MCPD.
What do you think ?

**Comment by BrapiCoordinatorSelby** [comment]
the `biologicalStatusOfAccessionCode` is pulled directly from the MCPD standard, so I want to keep the value in that field in sync with the standard. If you want to present something to users through a UI, MCPD is pretty clear on the name for each code, and that static mapping can be built into the users application. 

potentially we could add a new field like `biologicalStatusOfAccessionDescription` but I'm hesitant to do this because it opens up the potential for a mis-match between the code and the description.

**Comment by cpommier** [comment]
Discussion @BrapiCoordinatorSelby and I. We proposed to keep `biologicalStatusOfAccessionCode` as it is and add a biologicalStatusOfAccessionDescription with the text description, both non mandatory.
