### ISSUE TITLE
'value' missing for Germplasm Attributes

### ISSUE THREAD

**Issue by BrapiCoordinatorSelby** [plantbreeding/API#413]
Original Question from @GuilhemSempere 

> On january 8th you replied to me specifying that attributes?germplasmDbId={germplasmDbId} in V2 can be used as a replacement for germplasm/{germplasmDbId}/attributes in V1.3. However I'm not sure how to actually return attribute values in V2 because the "value" field seems to have disappeared from the response object (many others appeared though, so perhaps I'm missing something)

Response

> I'm so glad you asked this, you are totally correct, I really mucked this one up! I completely mixed up the concepts of Attribute Definition and Attribute Value.

Three ideas to resolve this off the top of my head:
Option 1 is to replace the '/germplasm/{dbid}/attributes' exactly as it was. 
Pros - really easy for me to do quickly
Cons - No way to upload (POST/PUT) new attribute values

Option 2 is to add 'value' and 'determinedDate' to the '/attribute' object. I thought it was there already, but I never really considered the ramifications of this. I would also need to add 'germplasmDbId' so that a value can be related to both a germplasm and an attribute definition. 
Pros - again, easy for me to do quickly. Could upload new attribute values with definition 
Cons - Messy, confusing the ideas of an attribute definition with and attribute value.

Option 3 is to create a '/attributeValues' entity. This would follow the Observations model a little better. 
There you have 'ObservationUnit' -> 'Observation' <- 'ObservationVariable' 
but here we would have 'Germplasm' -> 'Attribute Value' <- 'Attribute Definition'
Pros - clean, comprehensive model
Cons - A lot of new stuff to add right before v2.0 is supposed to be frozen

**Comment by jeback1** [comment]
I think option 3 is the way to go.  Posting new attribute values for existing attributes would seem a common use case.

**Comment by GuilhemSempere** [comment]
Hi

I have little experience with the (big) part of the API that does not relate to genotyping data so it's not easy for me to have a settled opinion on this.

But if Jan Erik confirms that option 3 is the best in the long term then indeed I would go for that because looking back at the experience we had with 1.0 I think delaying a release is a better compromise than adding hacky functionality that will probably become deprecated at some point.

G.



----- Mail original -----
De: "jeback1" <notifications@github.com>
À: "plantbreeding/API" <API@noreply.github.com>
Cc: "GuilhemSempere" <guilhem.sempere@cirad.fr>, "Mention" <mention@noreply.github.com>
Envoyé: Jeudi 30 Janvier 2020 03:43:58
Objet: Re: [plantbreeding/API] 'value' missing for Germplasm Attributes (#413)

I think option 3 is the way to go.  Posting new attribute values for existing attributes would seem a common use case.

**Comment by GuilhemSempere** [comment]
... btw, would option 3 allow querying attributes for multiple germplasm at a time?



----- Mail original -----
De: "Guilhem SEMPERE" <guilhem.sempere@cirad.fr>
À: "plantbreeding/API" <reply@reply.github.com>
Cc: "plantbreeding/API" <API@noreply.github.com>, "Mention" <mention@noreply.github.com>
Envoyé: Jeudi 30 Janvier 2020 08:37:07
Objet: Re: [plantbreeding/API] 'value' missing for Germplasm Attributes (#413)

Hi

I have little experience with the (big) part of the API that does not relate to genotyping data so it's not easy for me to have a settled opinion on this.

But if Jan Erik confirms that option 3 is the best in the long term then indeed I would go for that because looking back at the experience we had with 1.0 I think delaying a release is a better compromise than adding hacky functionality that will probably become deprecated at some point.

G.



----- Mail original -----
De: "jeback1" <notifications@github.com>
À: "plantbreeding/API" <API@noreply.github.com>
Cc: "GuilhemSempere" <guilhem.sempere@cirad.fr>, "Mention" <mention@noreply.github.com>
Envoyé: Jeudi 30 Janvier 2020 03:43:58
Objet: Re: [plantbreeding/API] 'value' missing for Germplasm Attributes (#413)

I think option 3 is the way to go.  Posting new attribute values for existing attributes would seem a common use case.

**Comment by BrapiCoordinatorSelby** [comment]
> ... btw, would option 3 allow querying attributes for multiple germplasm at a time?

Yes
