### ISSUE TITLE
POST -  /studies: use locationDbId instead of full location object

### ISSUE THREAD

**Issue by jeback1** [plantbreeding/API#418]
When posting new studies data, I think it would better to simply provide a locationDbId rather than the full location entity. Locations are complex entities; creating them de novo as part of the study creation process seems an unnecessary complication.

**Comment by BrapiCoordinatorSelby** [comment]
This is partially dependent on server implementation. When a server receives a POST with new study data, it could ignore all location fields except the locationDbId, and respond in error if that locationDbId doesn't already exist in the system. 

That said, I agree that since 'Locations' exist as a separate entity within BrAPI, it is sufficient for a Study to reference a locationDbId. This is how almost everything else works in BrAPI.

I can't find the original issue, but if I remember correctly, this happened because it was more efficient to have all the expanded location data present when retrieving a study, rather than getting location data separately. I recognise that your issue is talking about POSTing, but as a rule I would like to keep the same object between GET and POST
