### ISSUE TITLE
GET and POST /studies : change seasons[string] to seasons[object]

### ISSUE THREAD

**Issue by jeback1** [plantbreeding/API#434]
Since Seasons are entities with seasonDbId, I think it would be good to have the option of using the seasonDbId when creating (POST) new studies. To this end, seasons[string] could be replaced with seasons[object] where the object would have a seasonDbId field as well as a season field.

**Comment by cpommier** [comment]
In our system, the seasons (aka phenotypingCampaign) are not object on their own but simply labels allowing to group observationUnits within a study. It is therefore a simple text string on each observation. It is most of the time the equivalent of a year, represented as a string.
But there is an inconsistency because in /search/observationunits there is a "seasonDbIds": parameters which contain string examples ("spring 2018"). So I would propose to stick to seasons handled as string and to transform /search/observationunits {"seasonDbIds"} to  /search/observationunits {"seasons"}

**Comment by BrapiCoordinatorSelby** [comment]
#359

**Comment by jeback1** [comment]
For systems that don't treat seasons as entities, would it work to use the season field of a season object and ignore the seasonDbId?  Those systems wouldn't implement a POST service for creating new seasons. For /search/observationsunits, there could be two optional parameters: seasonDbId and season. 

So, a little bit more complicated for systems that don't treat seasons as entities in that the season string would have to be fished out of the season object but it seems manageable. On the other hand, not treating seasons as entities would force systems that do so to implement a non-BrAPI service in order to create new studies, etc.

**Comment by BrapiCoordinatorSelby** [comment]
Discussion with @jeback1 @cpommier 

Season object will keep its structure
```
{
    seasonDbId : "abc123",
    seasonName : "Breeding Cycle 1",
    year : "2019"
}
```

It will be promoted to a "first class" object within BrAPI, including GET, POST, PUT, and /search endpoints. 
It will be included in Study as a whole object, not just DbId reference. This will make it easier for systems with loosely defined seasons to ignore DbId if nessesary.
