### ISSUE TITLE
/brapi/v1/maps/{mapDbId}/positions?linkageGroupId variable naming

### ISSUE THREAD

**Issue by c5sire** [plantbreeding/API#51]
In the response object: should the variable 'linkageGroup' rather be named 'linkageGroupId' to correspond to the naming in the call? Or should both be named: 'linkageGroupDbId' to be consistent with other id names?

**Comment by BrapiCoordinatorSelby** [comment]
Open Question: Are you teams using linkageGroupId to represent a linkageGroupDbId as in a reference to a record in a database, or are you using it more like a linkageGroupName as in a reference to a particular group in a chromosome? Should both DbId and Name be available to query on or returned in the results?

I've reached out to a handful of people privately to see if I can get a consistent answer.

**Comment by c5sire** [comment]
My understanding was that all ¨-DbId¨were referring to a record in a database, while ¨-Name¨ would refer to a convenience name of a linkage group.

**Comment by BrapiCoordinatorSelby** [comment]
Yup @c5sire that is my understanding as well. Everyone I have talked to has agreed that the linkageGroupId parameter was assumed to mean linkageGroupName, or more specifically a chromosome number or subsection. It is NOT used as a database primary key.

For now, for version 1.1, we will change the name “linkageGroupId” to “linkageGroupName” and add a description in the documentation to clarify it as convenience genomic data instead of database key.

If anyone actually needs to track a "linkageGroupDbId" and can show me a good use case for it, we can add it later.
