### ISSUE TITLE
Missing Observed variables ID and PUI

### ISSUE THREAD

**Issue by cpommier** [plantbreeding/API#510]
In the specification of the Observed variables, I don't see the field for storing the ontology ID (eg CO_321:0000321). Likewise, having a PUI filed could be usefull (used in some information systems).
I would therefore suggest the following  adition : 
```
  "result": {
    "data": [
      {
        "method": {
          "methodDbId": "0adb2764",
          "methodID": "CO_123:2000012",
          "methodPUI": "http://my-minter.com/treait/CO_123:2000012",
        },
        "observationVariableDbId": "b9b7edd1",
        "observationVariableName": "Variable Name",
          "observationVariableID": "CO_123:1000012",
          "observationVariablePUI": "http://my-minter.com/treait/CO_123:1000012",
        "scale": {
          "scaleDbId": "af730171",
          "scaleName": "Meters",
          "scaleID": "CO_123:3000012",
          "scalePUI": "http://my-minter.com/treait/CO_123:3000012",
        },
        "trait": {
        
          "traitDbId": "9b2e34f5",
          "traitID": "CO_123:0000012",
          "traitPUI": "http://my-minter.com/treait/CO_123:0000012",
          "traitName": "Height"
        }
      }
    ]
  }
}
```

**Comment by cpommier** [comment]
Not so sure for the *ID field though, what do you think @BrapiCoordinatorSelby @marieALaporte

**Comment by BrapiCoordinatorSelby** [comment]
Hi @cpommier this looks reasonable to me. For now, you can use `externalReferences` to link the ID and PUI if needed as a work around.

**Comment by BrapiCoordinatorSelby** [comment]
From @cpommier in #527 

Currently we have observationVariableDbID:CO_356:1000037
But we don't have a way to store the URI of that ontology term: https://cropontology.org/rdf/CO_356:1000037
That would be much more W3C friendly, no?
Propose to add
observationVariablePUI:https://cropontology.org/rdf/CO_356:1000037

possibly the same for TraitDbID, addition of a traitPUI ?

**Comment by BrapiCoordinatorSelby** [comment]
From @cpommier in #486

In ObservationVariables:
```
"trait.attributePUI":"PO:00012345",
"trait.entityPUI":"PATO:00098765"
```

From @marieALaporte in #486 

I do not think that these fields should be linked to an ontology ID simply because not all the traits can be easily split into the Entity/attribute pattern. Often, you end up needing more than one ID to describe each field.
The Entity - Attribute fields were added to the CO TD in order to facilitate the definition of a trait. It worked in practice when someone is not sure if 2 similar traits are in fact one trait, or should be kept separated. But these fields for more complicated traits (e.g. leaf carbon content, seed dry weight, disease x susceptibility, ...) are not recorded in a consistent way depending on the ontology, which is a slightly different issue, but related in a way.

From @cpommier in #486

Hi @marieALaporte , the entity attribute are not always present/desirable, I totally agree. And they can be very messy. But they are increasingly used for defining traits and are therefore needed as optional fields.
