### ISSUE TITLE
Pagination: page requested above total number of pages

### ISSUE THREAD

**Issue by netbofia** [plantbreeding/API#84]
Hello i'm implementing the pagination part of the API response and I'm not sure what I'm supposed to return to a user when the page requested is above the total number of available pages:

Example:
total number of pages=10

page:2
pageSize:10 

  should the response simply be date: []  (No data)
    or
  should it be an error? 404

**Comment by gcornut** [comment]
We definitely need to document this kind of behavior in the API definition or in the wiki. 

We implemented it as a HTTP 200 response with an empty `data` array. 

It could also be a [HTTP 416 `"Range Not Satisfiable"`](https://developer.mozilla.org/fr/docs/Web/HTTP/Status/416) as it is normally returned by a server when the client sends an invalid `"Content-Range"` HTTP header that is conceptually very close to the `page` and `pageSize` parameters we use in the BrAPI.

I've started creating a wiki page on the subject in [Documentation/wiki/BrAPI-success-&-error-responses](https://github.com/plantbreeding/Documentation/wiki/BrAPI-success-&-error-responses)

It's just a first draft so don't hesitate to complete it.

I will soon also work on the Breeding API implementation here at INRA URGI and alongside the implementation I will try to enrich the wiki and the [BrAPI DataSet](https://github.com/plantbreeding/BrAPI-Dataset) for testing. Feel free to contribute!

**Comment by jackeblagare** [comment]
There were discussions already regarding standard API responses. The problem is, it's all over the place. I'll consolidate the discussions and add on the page that @gcornut created.

There are two categories of API responses: 1) Standard HTTP codes 2) API-specific codes. The first one includes HTTP 400, 500, etc. API implementations usually stick to a small subset of HTTP codes meaning only the common ones are used. Common ones include 401, 403, 404,405, 500, and 200 (of course). 

As for the second category, these are the more detailed ones (and user-friendly) responses that we define ourselves. This is also what you will usually see in the JSON response. An example would be a response when data validation fails.

As for the question of @netbofia regarding what to return, that can be a 400 (bad request). It won't be 404 because the resource exists but you're trying to force the resource to have something it doesn't.

**Comment by netbofia** [comment]
Thanks @gcornut that is a great idea. 
I'll try to keep note of all of these issues that come up. And add to it.

@jackeblagare yes either 400 or 416 depending on how specific we want to be.

Thanks
