### ISSUE TITLE
V2 Proposition: Merge germplasm attributes with observation variables

### ISSUE THREAD

**Issue by gcornut** [plantbreeding/API#99]
In our implementation of the BrAPI we've come to see that the germplasm attribute description is very much the same thing as an observation variable in the Breeding API. 

We would propose using the observation variable description to replace the germplasm attribute name, code and category (= observation variable trait class).

Example for the germplasm attributes call:
```json
/brapi/v1/germplasm/{germplasmDbId}/attributes
{
      "metadata" : {...},
      "result" : [
          {
              "germplasmDbId": "993",
              "data": [
                  {
                      "attributeDbId": "1",
                      "observationVariableDbId": "CO_325:0016351",
                      "observationVariableName": "HT",
                      "value": "Present", 
                      "determinedDate": "2007-05-28"
                  }
              ]
          }
      ]
  }
```

The attribute could also be represented as an observation (just like the phenotypic observation).

We should have a discussion on the use cases around the germplasm attributes and see if we could simplify the API by merging these concepts.

**Comment by jeback1** [comment]
Hi Guillaume,
Lukas and I discussed this today.  We both agree that the converging of attributes with observation variables would be a good idea but as it happens the BMS store doesn't store attributes as observation variables.  How could we make this call compatible with both approaches to storing attributes?
Thanks,
Jan Erik

**Comment by lukasmueller** [comment]
I would argue that we could also provide the observationVariableName right away in addition to the DbId, because that would have to be looked up in almost any case.

**Comment by gcornut** [comment]
@lukasmueller  Ok I'm adding the observationVariableName to the example.

@jeback1 Attributes and observation variables aren't stored in the same way in our system either but we planned to merge the entities as we think we would benefit from it. It can be difficult to merge these two concepts in implementation I agree. On relational database it could be done using a union query on the concerned tables (perhaps creating a view from this query for better performance).

**Comment by jeback1** [comment]
Using observationVariableName as the identifier implies that we expect that there is an underlying observation variable.  How about identifying the name as attributeName; systems that implement attributes as observation variables could using the observation variable name as the attribute name. If the oberservationVariableId is not null, the attributeName should match the obesrvationVariableName for that observation variable. For systems that don't implement attributes as observation variables, the observationVariableId would be null, reflecting that attributes were not implemented as observations variables.

**Comment by BrapiCoordinatorSelby** [comment]
@gcornut @jeback1 @lukasmueller Lets get this one resolved.

My interpretation of this issue and the subsequent comments is that 'germplasm attribute' is still an important concept to maintain separately from 'observation variable', but they are very similar concepts and the BrAPI 'observation variable' object has more detailed information (scale, method, trait, etc). 

Please correct me if my interpretation is wrong.

Instead of modifying '/germplasm/{germplasmDbId}/attributes', my proposed solution would be to enhance the '/attributes' call so that each 'germplasm attribute' object contained information similar to the 'observation variable' object. If a database stored variables and attributes in the same table, then both the '/attributes' call and '/variables' call would reference that same table. If not, then you still have the two separated concepts, germplasm reference attributes and observations reference variables.
